enum
{
	ETC_SINE90TXT,
	ETC_DATSTRINGS,

	// app >

	ENUM_RANGE(ETC_FLOOR_00, FLOOR_NUM)
	ETC_FLOOR_DUMMY,

	ETC_NOT_PRIME_POWER_101,
	ETC_NOT_PRIME_POWER_201,
	ETC_NOT_PRIME_POWER_301,
	ETC_NOT_PRIME_POWER_401,
	ETC_NOT_PRIME_POWER_501,
	ETC_PRIME,
	ETC_PRIME_POWER_101,
	ETC_PRIME_POWER_201,
	ETC_PRIME_POWER_301,
	ETC_PRIME_POWER_401,
	ETC_PRIME_POWER_501,

	// < app

	ETC_MAX, // num of member
};

oneObjectProto(resCluster<autoList<uchar> *>, GetEtcRes);
